CREATE CONSTRAINT ON (n:Neo4j) ASSERT n.version IS UNIQUE;
CREATE INDEX ON :SurfaceElement(name);
CREATE CONSTRAINT ON (s:Signature) ASSERT s.value IS UNIQUE;
CREATE CONSTRAINT ON (d:Description) ASSERT d.value IS UNIQUE;
CREATE CONSTRAINT ON (m:Mode) ASSERT m.value IS UNIQUE;
